#!/bin/bash

## If your config is not in ~/.config/glartex/config you must edit the script
export EDITOR="gedit"
export VIEWER="evince"
export BIBTEX="true"
export SYNCTEX="true"
export SWAY="false"

## Glartex supports the use of templates, default template must be in TEMPLATE_DIRECTORY
export TEMPLATE_DIRECTORY="${HOME}/.config/glartex/templates/"
export DEFAULT_TEMPLATE="${HOME}/.config/glartex/templates/basic.tex"

## Invoke a translation shell
export TRANSLATE="false"
export TARGET_LANGUAGE="ENG"
